# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  batch: true
  branches:
    include:
      - develop
      - feature/*
      - master
    exclude:
      - feature/dotnet3
      - feature/vNext
  paths:
    include:
      - .azure/*
      - demo/*
      - doc/*
      - src/*
      - test/*
      - WalkingTec.Mvvm.sln
      - common.props
      - version.props
      - NuGet.Config
      - .dockerignore
      - Dockerfile
      - wtmdoc.Dockerfile
    exclude:
      - .vscode/*
      - .travis.yml
      - .gitignore
      - .editorconfig
      - appveyor.yml
      - LICENSE
      - ./*.md
      - ./*.sh

pr:
  branches:
    include:
      - develop
      - feature/*
    exclude:
      - master
  paths:
    include:
      - .azure/*
      - demo/*
      - doc/*
      - src/*
      - test/*
      - WalkingTec.Mvvm.sln
      - common.props
      - version.props
      - NuGet.Config
      - .dockerignore
      - Dockerfile
      - wtmdoc.Dockerfile
    exclude:
      - .vscode/*
      - .travis.yml
      - .gitignore
      - .editorconfig
      - appveyor.yml
      - LICENSE
      - ./*.md
      - ./*.sh

jobs:
  - job: Linux
    pool:
      vmImage: "ubuntu-latest"

    variables:
      solution: "**/*.sln"
      buildPlatform: "Any CPU"
      buildConfiguration: "Release"

    steps:
      - task: DotNetCoreInstaller@1
        displayName: install
        inputs:
          version: "2.2.300"

      - task: DotNetCoreCLI@2
        displayName: restore
        inputs:
          command: "restore"
          projects: "$(solution)"
          feedsToUse: config
          nugetConfigPath: NuGet.Config
          arguments: "--configuration $(buildConfiguration)"

      - task: DotNetCoreCLI@2
        displayName: build
        inputs:
          command: "build"
          projects: "$(solution)"
          arguments: "--configuration $(buildConfiguration)"

      - task: DotNetCoreCLI@2
        displayName: test
        inputs:
          command: "test"
          testRunTitle: "test"
          arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

  - job: macOS
    pool:
      vmImage: "macOS-latest"

    variables:
      solution: "**/*.sln"
      buildPlatform: "Any CPU"
      buildConfiguration: "Release"

    steps:
      - task: DotNetCoreInstaller@1
        displayName: install
        inputs:
          version: "2.2.300"

      - task: DotNetCoreCLI@2
        displayName: restore
        inputs:
          command: "restore"
          projects: "$(solution)"
          feedsToUse: config
          nugetConfigPath: NuGet.Config
          arguments: "--configuration $(buildConfiguration)"

      - task: DotNetCoreCLI@2
        displayName: build
        inputs:
          command: "build"
          projects: "$(solution)"
          arguments: "--configuration $(buildConfiguration)"

      - task: DotNetCoreCLI@2
        displayName: test
        inputs:
          command: "test"
          testRunTitle: "test"
          arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

  - job: Windows
    pool:
      vmImage: "windows-latest"

    variables:
      solution: "**/*.sln"
      buildPlatform: "Any CPU"
      buildConfiguration: "Release"

    steps:
      - task: DotNetCoreInstaller@1
        displayName: install
        inputs:
          version: "2.2.300"

      - task: DotNetCoreCLI@2
        displayName: restore
        inputs:
          command: "restore"
          projects: "$(solution)"
          feedsToUse: config
          nugetConfigPath: NuGet.Config
          arguments: "--configuration $(buildConfiguration)"

      - task: DotNetCoreCLI@2
        displayName: build
        inputs:
          command: "build"
          projects: "$(solution)"
          arguments: "--configuration $(buildConfiguration)"

      - task: DotNetCoreCLI@2
        displayName: test
        inputs:
          command: "test"
          testRunTitle: "test"
          arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
