import './test/iconfont.css';
import './wtm/iconfont.css';
export default [
    {
        "name": "test",
        "class": "musicicon",
        "icons": [
            "musicicon-15",
            "musicicon-14",
            "musicicon-quanping",
            "musicicon-13",
            "musicicon-12",
            "musicicon-11",
            "musicicon-10",
            "musicicon-9",
            "musicicon-8",
            "musicicon-7",
            "musicicon-6",
            "musicicon-5",
            "musicicon-4",
            "musicicon-3",
            "musicicon-2",
            "musicicon-icon-",
            "musicicon-icon-1",
            "musicicon-icon-2",
            "musicicon-icon-3",
            "musicicon-1"
        ]
    },
    {
        "name": "wtm",
        "class": "_wtmicon",
        "icons": [
            "_wtmicon-renminbi",
            "_wtmicon-wxbzhanghu",
            "_wtmicon-wxbsousuotuiguang",
            "_wtmicon-iconfontmingpian",
            "_wtmicon-iconfontriyongbaihuo",
            "_wtmicon-file",
            "_wtmicon-tiaoshi",
            "_wtmicon-guanfangbanben",
            "_wtmicon-quanxianshenpi",
            "_wtmicon-yingyongguanli",
            "_wtmicon-zhanghaoquanxianguanli",
            "_wtmicon-folder",
            "_wtmicon-icon_shezhi",
            "_wtmicon-tubiao-bingtu",
            "_wtmicon-tubiao-qiapian",
            "_wtmicon-tubiao-zhexiantu",
            "_wtmicon-zuzhiqunzu",
            "_wtmicon-yingwen",
            "_wtmicon-zhongwen",
            "_wtmicon--lumingpai",
            "_wtmicon-fabu",
            "_wtmicon-xiayibu",
            "_wtmicon-shangyibu",
            "_wtmicon-xiangxiazhanhang",
            "_wtmicon-xiangshangzhanhang",
            "_wtmicon-tupianjiazaishibai",
            "_wtmicon-huanyuanhuabu",
            "_wtmicon-quanping",
            "_wtmicon-DOC",
            "_wtmicon-BMP",
            "_wtmicon-GIF",
            "_wtmicon-JPG",
            "_wtmicon-PNG",
            "_wtmicon-weizhigeshi",
            "_wtmicon-yunduanxiazai",
            "_wtmicon-yunduanshangchuan",
            "_wtmicon-wentijieda",
            "_wtmicon-dingwei",
            "_wtmicon-xiaoxitongzhi",
            "_wtmicon-xinhao",
            "_wtmicon-lanya",
            "_wtmicon-Wi-Fi",
            "_wtmicon-chaxun",
            "_wtmicon-anquan",
            "_wtmicon-hanshu",
            "_wtmicon-chucun",
            "_wtmicon-bug",
            "_wtmicon-js",
            "_wtmicon-wuxiandianbo",
            "_wtmicon-dianzan_kuai",
            "_wtmicon-zhihuan",
            "_wtmicon-aixin_shixin",
            "_wtmicon-aixin",
            "_wtmicon-shengyin_shiti",
            "_wtmicon-shengyinkai",
            "_wtmicon-shoucang_shixin",
            "_wtmicon-shoucang",
            "_wtmicon-shengyinwu",
            "_wtmicon-shengyinjingyin",
            "_wtmicon-fenxiangfangshi"
        ]
    }
] 