//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalkingTec.Mvvm.BlazorDemo.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Program {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Program() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WalkingTec.Mvvm.BlazorDemo.Shared.Resources.Program", typeof(Program).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 账号 的本地化字符串。
        /// </summary>
        public static string _Admin_Account {
            get {
                return ResourceManager.GetString("_Admin.Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动作 的本地化字符串。
        /// </summary>
        public static string _Admin_Action {
            get {
                return ResourceManager.GetString("_Admin.Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志管理Api 的本地化字符串。
        /// </summary>
        public static string _Admin_ActionLogApi {
            get {
                return ResourceManager.GetString("_Admin.ActionLogApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动作名称 的本地化字符串。
        /// </summary>
        public static string _Admin_ActionName {
            get {
                return ResourceManager.GetString("_Admin.ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作时间 的本地化字符串。
        /// </summary>
        public static string _Admin_ActionTime {
            get {
                return ResourceManager.GetString("_Admin.ActionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附加信息 的本地化字符串。
        /// </summary>
        public static string _Admin_AdditionInfo {
            get {
                return ResourceManager.GetString("_Admin.AdditionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string _Admin_Address {
            get {
                return ResourceManager.GetString("_Admin.Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部权限 的本地化字符串。
        /// </summary>
        public static string _Admin_AllDp {
            get {
                return ResourceManager.GetString("_Admin.AllDp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许 的本地化字符串。
        /// </summary>
        public static string _Admin_Allowed {
            get {
                return ResourceManager.GetString("_Admin.Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许访问 的本地化字符串。
        /// </summary>
        public static string _Admin_AllowedDp {
            get {
                return ResourceManager.GetString("_Admin.AllowedDp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许角色 的本地化字符串。
        /// </summary>
        public static string _Admin_AllowedRole {
            get {
                return ResourceManager.GetString("_Admin.AllowedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部权限 的本地化字符串。
        /// </summary>
        public static string _Admin_AllPris {
            get {
                return ResourceManager.GetString("_Admin.AllPris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本信息 的本地化字符串。
        /// </summary>
        public static string _Admin_BasicInfo {
            get {
                return ResourceManager.GetString("_Admin.BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机 的本地化字符串。
        /// </summary>
        public static string _Admin_CellPhone {
            get {
                return ResourceManager.GetString("_Admin.CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查页面 的本地化字符串。
        /// </summary>
        public static string _Admin_CheckPage {
            get {
                return ResourceManager.GetString("_Admin.CheckPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类名 的本地化字符串。
        /// </summary>
        public static string _Admin_ClassName {
            get {
                return ResourceManager.GetString("_Admin.ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string _Admin_CreateBy {
            get {
                return ResourceManager.GetString("_Admin.CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string _Admin_CreateTime {
            get {
                return ResourceManager.GetString("_Admin.CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据权限 的本地化字符串。
        /// </summary>
        public static string _Admin_DataPrivilege {
            get {
                return ResourceManager.GetString("_Admin.DataPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据权限Api 的本地化字符串。
        /// </summary>
        public static string _Admin_DataPrivilegeApi {
            get {
                return ResourceManager.GetString("_Admin.DataPrivilegeApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限数量 的本地化字符串。
        /// </summary>
        public static string _Admin_DataPrivilegeCount {
            get {
                return ResourceManager.GetString("_Admin.DataPrivilegeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限名称 的本地化字符串。
        /// </summary>
        public static string _Admin_DataPrivilegeName {
            get {
                return ResourceManager.GetString("_Admin.DataPrivilegeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试 的本地化字符串。
        /// </summary>
        public static string _Admin_Debug {
            get {
                return ResourceManager.GetString("_Admin.Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顺序 的本地化字符串。
        /// </summary>
        public static string _Admin_DisplayOrder {
            get {
                return ResourceManager.GetString("_Admin.DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 域 的本地化字符串。
        /// </summary>
        public static string _Admin_Domain {
            get {
                return ResourceManager.GetString("_Admin.Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权对象 的本地化字符串。
        /// </summary>
        public static string _Admin_DpTargetName {
            get {
                return ResourceManager.GetString("_Admin.DpTargetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限类别 的本地化字符串。
        /// </summary>
        public static string _Admin_DpType {
            get {
                return ResourceManager.GetString("_Admin.DpType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时长 的本地化字符串。
        /// </summary>
        public static string _Admin_Duration {
            get {
                return ResourceManager.GetString("_Admin.Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        public static string _Admin_Email {
            get {
                return ResourceManager.GetString("_Admin.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        public static string _Admin_Exception {
            get {
                return ResourceManager.GetString("_Admin.Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段名称 的本地化字符串。
        /// </summary>
        public static string _Admin_FieldName {
            get {
                return ResourceManager.GetString("_Admin.FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件操作Api 的本地化字符串。
        /// </summary>
        public static string _Admin_FileApi {
            get {
                return ResourceManager.GetString("_Admin.FileApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展名 的本地化字符串。
        /// </summary>
        public static string _Admin_FileExt {
            get {
                return ResourceManager.GetString("_Admin.FileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录 的本地化字符串。
        /// </summary>
        public static string _Admin_FolderOnly {
            get {
                return ResourceManager.GetString("_Admin.FolderOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string _Admin_Gender {
            get {
                return ResourceManager.GetString("_Admin.Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组 的本地化字符串。
        /// </summary>
        public static string _Admin_Group {
            get {
                return ResourceManager.GetString("_Admin.Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组管理Api 的本地化字符串。
        /// </summary>
        public static string _Admin_GroupApi {
            get {
                return ResourceManager.GetString("_Admin.GroupApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组编号 的本地化字符串。
        /// </summary>
        public static string _Admin_GroupCode {
            get {
                return ResourceManager.GetString("_Admin.GroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组权限 的本地化字符串。
        /// </summary>
        public static string _Admin_GroupDp {
            get {
                return ResourceManager.GetString("_Admin.GroupDp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组名 的本地化字符串。
        /// </summary>
        public static string _Admin_GroupName {
            get {
                return ResourceManager.GetString("_Admin.GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 座机 的本地化字符串。
        /// </summary>
        public static string _Admin_HomePhone {
            get {
                return ResourceManager.GetString("_Admin.HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标 的本地化字符串。
        /// </summary>
        public static string _Admin_Icon {
            get {
                return ResourceManager.GetString("_Admin.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标库 的本地化字符串。
        /// </summary>
        public static string _Admin_IconFont {
            get {
                return ResourceManager.GetString("_Admin.IconFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部 的本地化字符串。
        /// </summary>
        public static string _Admin_Inside {
            get {
                return ResourceManager.GetString("_Admin.Inside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继承 的本地化字符串。
        /// </summary>
        public static string _Admin_IsInherit {
            get {
                return ResourceManager.GetString("_Admin.IsInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部地址 的本地化字符串。
        /// </summary>
        public static string _Admin_IsInside {
            get {
                return ResourceManager.GetString("_Admin.IsInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公开 的本地化字符串。
        /// </summary>
        public static string _Admin_IsPublic {
            get {
                return ResourceManager.GetString("_Admin.IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效 的本地化字符串。
        /// </summary>
        public static string _Admin_IsValid {
            get {
                return ResourceManager.GetString("_Admin.IsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        public static string _Admin_Length {
            get {
                return ResourceManager.GetString("_Admin.Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号操作Api 的本地化字符串。
        /// </summary>
        public static string _Admin_LoginApi {
            get {
                return ResourceManager.GetString("_Admin.LoginApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string _Admin_LogType {
            get {
                return ResourceManager.GetString("_Admin.LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单管理Api 的本地化字符串。
        /// </summary>
        public static string _Admin_MenuApi {
            get {
                return ResourceManager.GetString("_Admin.MenuApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单项 的本地化字符串。
        /// </summary>
        public static string _Admin_MenuItem {
            get {
                return ResourceManager.GetString("_Admin.MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法 的本地化字符串。
        /// </summary>
        public static string _Admin_MethodName {
            get {
                return ResourceManager.GetString("_Admin.MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块 的本地化字符串。
        /// </summary>
        public static string _Admin_Module {
            get {
                return ResourceManager.GetString("_Admin.Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该模块已经配置过了 的本地化字符串。
        /// </summary>
        public static string _Admin_ModuleHasSet {
            get {
                return ResourceManager.GetString("_Admin.ModuleHasSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string _Admin_Name {
            get {
                return ResourceManager.GetString("_Admin.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块中没有找到Index页面 的本地化字符串。
        /// </summary>
        public static string _Admin_NoIndexInModule {
            get {
                return ResourceManager.GetString("_Admin.NoIndexInModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无权限 的本地化字符串。
        /// </summary>
        public static string _Admin_NoPris {
            get {
                return ResourceManager.GetString("_Admin.NoPris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通 的本地化字符串。
        /// </summary>
        public static string _Admin_Normal {
            get {
                return ResourceManager.GetString("_Admin.Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外部 的本地化字符串。
        /// </summary>
        public static string _Admin_Outside {
            get {
                return ResourceManager.GetString("_Admin.Outside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面权限 的本地化字符串。
        /// </summary>
        public static string _Admin_PageFunction {
            get {
                return ResourceManager.GetString("_Admin.PageFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面名称 的本地化字符串。
        /// </summary>
        public static string _Admin_PageName {
            get {
                return ResourceManager.GetString("_Admin.PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父级 的本地化字符串。
        /// </summary>
        public static string _Admin_Parent {
            get {
                return ResourceManager.GetString("_Admin.Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父目录 的本地化字符串。
        /// </summary>
        public static string _Admin_ParentFolder {
            get {
                return ResourceManager.GetString("_Admin.ParentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string _Admin_Password {
            get {
                return ResourceManager.GetString("_Admin.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径 的本地化字符串。
        /// </summary>
        public static string _Admin_Path {
            get {
                return ResourceManager.GetString("_Admin.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片 的本地化字符串。
        /// </summary>
        public static string _Admin_Photo {
            get {
                return ResourceManager.GetString("_Admin.Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        public static string _Admin_Privileges {
            get {
                return ResourceManager.GetString("_Admin.Privileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新菜单 的本地化字符串。
        /// </summary>
        public static string _Admin_RefreshMenu {
            get {
                return ResourceManager.GetString("_Admin.RefreshMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string _Admin_Remark {
            get {
                return ResourceManager.GetString("_Admin.Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string _Admin_Role {
            get {
                return ResourceManager.GetString("_Admin.Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理Api 的本地化字符串。
        /// </summary>
        public static string _Admin_RoleApi {
            get {
                return ResourceManager.GetString("_Admin.RoleApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色编号 的本地化字符串。
        /// </summary>
        public static string _Admin_RoleCode {
            get {
                return ResourceManager.GetString("_Admin.RoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名称 的本地化字符串。
        /// </summary>
        public static string _Admin_RoleName {
            get {
                return ResourceManager.GetString("_Admin.RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择模型 的本地化字符串。
        /// </summary>
        public static string _Admin_SelectedModel {
            get {
                return ResourceManager.GetString("_Admin.SelectedModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择权限 的本地化字符串。
        /// </summary>
        public static string _Admin_SelectPris {
            get {
                return ResourceManager.GetString("_Admin.SelectPris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单显示 的本地化字符串。
        /// </summary>
        public static string _Admin_ShowOnMenu {
            get {
                return ResourceManager.GetString("_Admin.ShowOnMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限名称 的本地化字符串。
        /// </summary>
        public static string _Admin_TableName {
            get {
                return ResourceManager.GetString("_Admin.TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 租户 的本地化字符串。
        /// </summary>
        public static string _Admin_Tenant {
            get {
                return ResourceManager.GetString("_Admin.Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置页面 的本地化字符串。
        /// </summary>
        public static string _Admin_UnsetPages {
            get {
                return ResourceManager.GetString("_Admin.UnsetPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改人 的本地化字符串。
        /// </summary>
        public static string _Admin_UpdateBy {
            get {
                return ResourceManager.GetString("_Admin.UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改时间 的本地化字符串。
        /// </summary>
        public static string _Admin_UpdateTime {
            get {
                return ResourceManager.GetString("_Admin.UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string _Admin_User {
            get {
                return ResourceManager.GetString("_Admin.User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理Api 的本地化字符串。
        /// </summary>
        public static string _Admin_UserApi {
            get {
                return ResourceManager.GetString("_Admin.UserApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户权限 的本地化字符串。
        /// </summary>
        public static string _Admin_UserDp {
            get {
                return ResourceManager.GetString("_Admin.UserDp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含用户 的本地化字符串。
        /// </summary>
        public static string _Admin_UsersCount {
            get {
                return ResourceManager.GetString("_Admin.UsersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮编 的本地化字符串。
        /// </summary>
        public static string _Admin_ZipCode {
            get {
                return ResourceManager.GetString("_Admin.ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选此项将只生成api，而没有前端代码 的本地化字符串。
        /// </summary>
        public static string Codegen_ApiOnly {
            get {
                return ResourceManager.GetString("Codegen.ApiOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件 的本地化字符串。
        /// </summary>
        public static string Codegen_Attachment {
            get {
                return ResourceManager.GetString("Codegen.Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 认证方式 的本地化字符串。
        /// </summary>
        public static string Codegen_AuthMode {
            get {
                return ResourceManager.GetString("Codegen.AuthMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该操作将生成如下文件，是否确定？ 的本地化字符串。
        /// </summary>
        public static string Codegen_Confirm {
            get {
                return ResourceManager.GetString("Codegen.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller命名空间 的本地化字符串。
        /// </summary>
        public static string Codegen_ControllerNs {
            get {
                return ResourceManager.GetString("Codegen.ControllerNs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data命名空间 的本地化字符串。
        /// </summary>
        public static string Codegen_DataNs {
            get {
                return ResourceManager.GetString("Codegen.DataNs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}只能以英文字母或下划线开头 的本地化字符串。
        /// </summary>
        public static string Codegen_EnglishOnly {
            get {
                return ResourceManager.GetString("Codegen.EnglishOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段描述 的本地化字符串。
        /// </summary>
        public static string Codegen_FieldDes {
            get {
                return ResourceManager.GetString("Codegen.FieldDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        public static string Codegen_FileName {
            get {
                return ResourceManager.GetString("Codegen.FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成代码 的本地化字符串。
        /// </summary>
        public static string Codegen_Gen {
            get {
                return ResourceManager.GetString("Codegen.Gen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成Api 的本地化字符串。
        /// </summary>
        public static string Codegen_GenApi {
            get {
                return ResourceManager.GetString("Codegen.GenApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入模块名称，比如xx管理 的本地化字符串。
        /// </summary>
        public static string Codegen_InputModuleName {
            get {
                return ResourceManager.GetString("Codegen.InputModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量更新字段 的本地化字符串。
        /// </summary>
        public static string Codegen_IsBatchField {
            get {
                return ResourceManager.GetString("Codegen.IsBatchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单字段 的本地化字符串。
        /// </summary>
        public static string Codegen_IsFormField {
            get {
                return ResourceManager.GetString("Codegen.IsFormField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入字段 的本地化字符串。
        /// </summary>
        public static string Codegen_IsImportField {
            get {
                return ResourceManager.GetString("Codegen.IsImportField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表展示 的本地化字符串。
        /// </summary>
        public static string Codegen_IsListField {
            get {
                return ResourceManager.GetString("Codegen.IsListField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索条件 的本地化字符串。
        /// </summary>
        public static string Codegen_IsSearcherField {
            get {
                return ResourceManager.GetString("Codegen.IsSearcherField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联类型 的本地化字符串。
        /// </summary>
        public static string Codegen_LinkedType {
            get {
                return ResourceManager.GetString("Codegen.LinkedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多对多 的本地化字符串。
        /// </summary>
        public static string Codegen_ManyToMany {
            get {
                return ResourceManager.GetString("Codegen.ManyToMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model命名空间 的本地化字符串。
        /// </summary>
        public static string Codegen_ModelNS {
            get {
                return ResourceManager.GetString("Codegen.ModelNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块名称 的本地化字符串。
        /// </summary>
        public static string Codegen_ModuleName {
            get {
                return ResourceManager.GetString("Codegen.ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一对多 的本地化字符串。
        /// </summary>
        public static string Codegen_OneToMany {
            get {
                return ResourceManager.GetString("Codegen.OneToMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所选模型必须继承TopBasePoco基类 的本地化字符串。
        /// </summary>
        public static string Codegen_SelectedModelMustBeBasePoco {
            get {
                return ResourceManager.GetString("Codegen.SelectedModelMustBeBasePoco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个模块 的本地化字符串。
        /// </summary>
        public static string Codegen_SelectModule {
            get {
                return ResourceManager.GetString("Codegen.SelectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请进行字段配置 的本地化字符串。
        /// </summary>
        public static string Codegen_Setup {
            get {
                return ResourceManager.GetString("Codegen.Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始生成 的本地化字符串。
        /// </summary>
        public static string Codegen_Start {
            get {
                return ResourceManager.GetString("Codegen.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联表显示字段 的本地化字符串。
        /// </summary>
        public static string Codegen_SubField {
            get {
                return ResourceManager.GetString("Codegen.SubField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成成功！请关闭调试重新编译运行 的本地化字符串。
        /// </summary>
        public static string Codegen_Success {
            get {
                return ResourceManager.GetString("Codegen.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test命名空间 的本地化字符串。
        /// </summary>
        public static string Codegen_TestNs {
            get {
                return ResourceManager.GetString("Codegen.TestNs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VM命名空间 的本地化字符串。
        /// </summary>
        public static string Codegen_VMNs {
            get {
                return ResourceManager.GetString("Codegen.VMNs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string Login_ChangePassword {
            get {
                return ResourceManager.GetString("Login.ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码修改成功，下次请使用新密码登录。 的本地化字符串。
        /// </summary>
        public static string Login_ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("Login.ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码 的本地化字符串。
        /// </summary>
        public static string Login_InputPassword {
            get {
                return ResourceManager.GetString("Login.InputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户名 的本地化字符串。
        /// </summary>
        public static string Login_InputUserName {
            get {
                return ResourceManager.GetString("Login.InputUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入验证码 的本地化字符串。
        /// </summary>
        public static string Login_InputValidation {
            get {
                return ResourceManager.GetString("Login.InputValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号重复 的本地化字符串。
        /// </summary>
        public static string Login_ItcodeDuplicate {
            get {
                return ResourceManager.GetString("Login.ItcodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登 录 的本地化字符串。
        /// </summary>
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string Login_LogOut {
            get {
                return ResourceManager.GetString("Login.LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        public static string Login_NewPassword {
            get {
                return ResourceManager.GetString("Login.NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        public static string Login_NewPasswordComfirm {
            get {
                return ResourceManager.GetString("Login.NewPasswordComfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前密码 的本地化字符串。
        /// </summary>
        public static string Login_OldPassword {
            get {
                return ResourceManager.GetString("Login.OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前密码错误 的本地化字符串。
        /// </summary>
        public static string Login_OldPasswrodWrong {
            get {
                return ResourceManager.GetString("Login.OldPasswrodWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两次新密码输入不一致 的本地化字符串。
        /// </summary>
        public static string Login_PasswordNotSame {
            get {
                return ResourceManager.GetString("Login.PasswordNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注 册 的本地化字符串。
        /// </summary>
        public static string Login_Register {
            get {
                return ResourceManager.GetString("Login.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新用户注册 的本地化字符串。
        /// </summary>
        public static string Login_RegTitle {
            get {
                return ResourceManager.GetString("Login.RegTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住我 的本地化字符串。
        /// </summary>
        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login.RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码不正确 的本地化字符串。
        /// </summary>
        public static string Login_ValidationFail {
            get {
                return ResourceManager.GetString("Login.ValidationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        public static string MenuKey_ActionLog {
            get {
                return ResourceManager.GetString("MenuKey.ActionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内置Api 的本地化字符串。
        /// </summary>
        public static string MenuKey_Api {
            get {
                return ResourceManager.GetString("MenuKey.Api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据权限 的本地化字符串。
        /// </summary>
        public static string MenuKey_DataPrivilege {
            get {
                return ResourceManager.GetString("MenuKey.DataPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组管理 的本地化字符串。
        /// </summary>
        public static string MenuKey_GroupManagement {
            get {
                return ResourceManager.GetString("MenuKey.GroupManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string MenuKey_Login {
            get {
                return ResourceManager.GetString("MenuKey.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单管理 的本地化字符串。
        /// </summary>
        public static string MenuKey_MenuMangement {
            get {
                return ResourceManager.GetString("MenuKey.MenuMangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理 的本地化字符串。
        /// </summary>
        public static string MenuKey_RoleManagement {
            get {
                return ResourceManager.GetString("MenuKey.RoleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统管理 的本地化字符串。
        /// </summary>
        public static string MenuKey_SystemManagement {
            get {
                return ResourceManager.GetString("MenuKey.SystemManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string MenuKey_UserManagement {
            get {
                return ResourceManager.GetString("MenuKey.UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单管理 的本地化字符串。
        /// </summary>
        public static string MenuMangement {
            get {
                return ResourceManager.GetString("MenuMangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册成功 的本地化字符串。
        /// </summary>
        public static string Reg_Success {
            get {
                return ResourceManager.GetString("Reg.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}格式错误 的本地化字符串。
        /// </summary>
        public static string Sys__0_formaterror {
            get {
                return ResourceManager.GetString("Sys.{0}formaterror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}输入的值在数据库中不存在 的本地化字符串。
        /// </summary>
        public static string Sys__0_ValueNotExist {
            get {
                return ResourceManager.GetString("Sys.{0}ValueNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}输入的值不在允许的数据类型范围内 的本地化字符串。
        /// </summary>
        public static string Sys__0_ValueTypeNotAllowed {
            get {
                return ResourceManager.GetString("Sys.{0}ValueTypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号 的本地化字符串。
        /// </summary>
        public static string Sys_Account {
            get {
                return ResourceManager.GetString("Sys.Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超级管理员 的本地化字符串。
        /// </summary>
        public static string Sys_Admin {
            get {
                return ResourceManager.GetString("Sys.Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string Sys_All {
            get {
                return ResourceManager.GetString("Sys.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Api文档 的本地化字符串。
        /// </summary>
        public static string Sys_ApiDoc {
            get {
                return ResourceManager.GetString("Sys.ApiDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; 不是 {1} 的有效格式 的本地化字符串。
        /// </summary>
        public static string Sys_AttemptedValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("Sys.AttemptedValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回首页 的本地化字符串。
        /// </summary>
        public static string Sys_BackHome {
            get {
                return ResourceManager.GetString("Sys.BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量删除 的本地化字符串。
        /// </summary>
        public static string Sys_BatchDelete {
            get {
                return ResourceManager.GetString("Sys.BatchDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除以下数据么： 的本地化字符串。
        /// </summary>
        public static string Sys_BatchDeleteConfirm {
            get {
                return ResourceManager.GetString("Sys.BatchDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功删除{0}行数据 的本地化字符串。
        /// </summary>
        public static string Sys_BatchDeleteSuccess {
            get {
                return ResourceManager.GetString("Sys.BatchDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量修改 的本地化字符串。
        /// </summary>
        public static string Sys_BatchEdit {
            get {
                return ResourceManager.GetString("Sys.BatchEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量修改以下数据 的本地化字符串。
        /// </summary>
        public static string Sys_BatchEditConfirm {
            get {
                return ResourceManager.GetString("Sys.BatchEditConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功修改{0}行数据 的本地化字符串。
        /// </summary>
        public static string Sys_BatchEditSuccess {
            get {
                return ResourceManager.GetString("Sys.BatchEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}已被使用，无法删除 的本地化字符串。
        /// </summary>
        public static string Sys_CannotDelete {
            get {
                return ResourceManager.GetString("Sys.CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到账号为{0}的用户 的本地化字符串。
        /// </summary>
        public static string Sys_CannotFindUser {
            get {
                return ResourceManager.GetString("Sys.CannotFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列号 的本地化字符串。
        /// </summary>
        public static string Sys_CellIndex {
            get {
                return ResourceManager.GetString("Sys.CellIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选导出 的本地化字符串。
        /// </summary>
        public static string Sys_CheckExport {
            get {
                return ResourceManager.GetString("Sys.CheckExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Sys_Close {
            get {
                return ResourceManager.GetString("Sys.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭全部标签页 的本地化字符串。
        /// </summary>
        public static string Sys_CloseAllTags {
            get {
                return ResourceManager.GetString("Sys.CloseAllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭其它标签页 的本地化字符串。
        /// </summary>
        public static string Sys_CloseOtherTags {
            get {
                return ResourceManager.GetString("Sys.CloseOtherTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭当前标签页 的本地化字符串。
        /// </summary>
        public static string Sys_CloseThisTag {
            get {
                return ResourceManager.GetString("Sys.CloseThisTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码生成器 的本地化字符串。
        /// </summary>
        public static string Sys_CodeGen {
            get {
                return ResourceManager.GetString("Sys.CodeGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选列 的本地化字符串。
        /// </summary>
        public static string Sys_ColumnFilter {
            get {
                return ResourceManager.GetString("Sys.ColumnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下拉菜单 的本地化字符串。
        /// </summary>
        public static string Sys_ComboBox {
            get {
                return ResourceManager.GetString("Sys.ComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        public static string Sys_Continue {
            get {
                return ResourceManager.GetString("Sys.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        public static string Sys_Create {
            get {
                return ResourceManager.GetString("Sys.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据被使用，无法删除 的本地化字符串。
        /// </summary>
        public static string Sys_DataCannotDelete {
            get {
                return ResourceManager.GetString("Sys.DataCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据不存在 的本地化字符串。
        /// </summary>
        public static string Sys_DataNotExist {
            get {
                return ResourceManager.GetString("Sys.DataNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在{0}到{1}之间 的本地化字符串。
        /// </summary>
        public static string Sys_DataRange {
            get {
                return ResourceManager.GetString("Sys.DataRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该地址只能在调试模式下访问 的本地化字符串。
        /// </summary>
        public static string Sys_DebugOnly {
            get {
                return ResourceManager.GetString("Sys.DebugOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认区域 的本地化字符串。
        /// </summary>
        public static string Sys_DefaultArea {
            get {
                return ResourceManager.GetString("Sys.DefaultArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Sys_Delete {
            get {
                return ResourceManager.GetString("Sys.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除这条数据么： 的本地化字符串。
        /// </summary>
        public static string Sys_DeleteConfirm {
            get {
                return ResourceManager.GetString("Sys.DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据使用中，无法删除 的本地化字符串。
        /// </summary>
        public static string Sys_DeleteFailed {
            get {
                return ResourceManager.GetString("Sys.DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细 的本地化字符串。
        /// </summary>
        public static string Sys_Details {
            get {
                return ResourceManager.GetString("Sys.Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 的本地化字符串。
        /// </summary>
        public static string Sys_Download {
            get {
                return ResourceManager.GetString("Sys.Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载模板 的本地化字符串。
        /// </summary>
        public static string Sys_DownloadTemplate {
            get {
                return ResourceManager.GetString("Sys.DownloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}数据重复 的本地化字符串。
        /// </summary>
        public static string Sys_DuplicateError {
            get {
                return ResourceManager.GetString("Sys.DuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}组合字段重复 的本地化字符串。
        /// </summary>
        public static string Sys_DuplicateGroupError {
            get {
                return ResourceManager.GetString("Sys.DuplicateGroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Sys_Edit {
            get {
                return ResourceManager.GetString("Sys.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改失败 的本地化字符串。
        /// </summary>
        public static string Sys_EditFailed {
            get {
                return ResourceManager.GetString("Sys.EditFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string Sys_Enable {
            get {
                return ResourceManager.GetString("Sys.Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Sys_Error {
            get {
                return ResourceManager.GetString("Sys.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误处理 的本地化字符串。
        /// </summary>
        public static string Sys_ErrorHandle {
            get {
                return ResourceManager.GetString("Sys.ErrorHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误信息 的本地化字符串。
        /// </summary>
        public static string Sys_ErrorMsg {
            get {
                return ResourceManager.GetString("Sys.ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Sys_Export {
            get {
                return ResourceManager.GetString("Sys.Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选导出 的本地化字符串。
        /// </summary>
        public static string Sys_ExportByIds {
            get {
                return ResourceManager.GetString("Sys.ExportByIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出Excel 的本地化字符串。
        /// </summary>
        public static string Sys_ExportExcel {
            get {
                return ResourceManager.GetString("Sys.ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取数据失败 的本地化字符串。
        /// </summary>
        public static string Sys_FailedLoadData {
            get {
                return ResourceManager.GetString("Sys.FailedLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 女 的本地化字符串。
        /// </summary>
        public static string Sys_Female {
            get {
                return ResourceManager.GetString("Sys.Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到文件 的本地化字符串。
        /// </summary>
        public static string Sys_FileNotFound {
            get {
                return ResourceManager.GetString("Sys.FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待选择 的本地化字符串。
        /// </summary>
        public static string Sys_ForSelect {
            get {
                return ResourceManager.GetString("Sys.ForSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 的本地化字符串。
        /// </summary>
        public static string Sys_Get {
            get {
                return ResourceManager.GetString("Sys.Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到第 的本地化字符串。
        /// </summary>
        public static string Sys_Goto {
            get {
                return ResourceManager.GetString("Sys.Goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Sys_GotoButtonText {
            get {
                return ResourceManager.GetString("Sys.GotoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有 的本地化字符串。
        /// </summary>
        public static string Sys_Have {
            get {
                return ResourceManager.GetString("Sys.Have", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 侧边伸缩 的本地化字符串。
        /// </summary>
        public static string Sys_HideShow {
            get {
                return ResourceManager.GetString("Sys.HideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string Sys_Import {
            get {
                return ResourceManager.GetString("Sys.Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入时发生错误 的本地化字符串。
        /// </summary>
        public static string Sys_ImportError {
            get {
                return ResourceManager.GetString("Sys.ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功导入{0}行数据 的本地化字符串。
        /// </summary>
        public static string Sys_ImportSuccess {
            get {
                return ResourceManager.GetString("Sys.ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string Sys_Info {
            get {
                return ResourceManager.GetString("Sys.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效 的本地化字符串。
        /// </summary>
        public static string Sys_Invalid {
            get {
                return ResourceManager.GetString("Sys.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CN 的本地化字符串。
        /// </summary>
        public static string Sys_LayuiDateLan {
            get {
                return ResourceManager.GetString("Sys.LayuiDateLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载失败 的本地化字符串。
        /// </summary>
        public static string Sys_LoadFailed {
            get {
                return ResourceManager.GetString("Sys.LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败 的本地化字符串。
        /// </summary>
        public static string Sys_LoginFailed {
            get {
                return ResourceManager.GetString("Sys.LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页面 的本地化字符串。
        /// </summary>
        public static string Sys_MainPage {
            get {
                return ResourceManager.GetString("Sys.MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 男 的本地化字符串。
        /// </summary>
        public static string Sys_Male {
            get {
                return ResourceManager.GetString("Sys.Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您没有登录或登录已过期，请重新登陆 的本地化字符串。
        /// </summary>
        public static string Sys_NeedLogin {
            get {
                return ResourceManager.GetString("Sys.NeedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string Sys_No {
            get {
                return ResourceManager.GetString("Sys.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无数据 的本地化字符串。
        /// </summary>
        public static string Sys_NoData {
            get {
                return ResourceManager.GetString("Sys.NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无匹配数据 的本地化字符串。
        /// </summary>
        public static string Sys_NoMatchingData {
            get {
                return ResourceManager.GetString("Sys.NoMatchingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        public static string Sys_None {
            get {
                return ResourceManager.GetString("Sys.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您没有访问该页面的权限 的本地化字符串。
        /// </summary>
        public static string Sys_NoPrivilege {
            get {
                return ResourceManager.GetString("Sys.NoPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        public static string Sys_NotHave {
            get {
                return ResourceManager.GetString("Sys.NotHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Sys_OK {
            get {
                return ResourceManager.GetString("Sys.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Sys_Operation {
            get {
                return ResourceManager.GetString("Sys.Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        public static string Sys_OprationSuccess {
            get {
                return ResourceManager.GetString("Sys.OprationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页 的本地化字符串。
        /// </summary>
        public static string Sys_Page {
            get {
                return ResourceManager.GetString("Sys.Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面发生错误 的本地化字符串。
        /// </summary>
        public static string Sys_PageError {
            get {
                return ResourceManager.GetString("Sys.PageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入小数 的本地化字符串。
        /// </summary>
        public static string Sys_PleaseInputDecimal {
            get {
                return ResourceManager.GetString("Sys.PleaseInputDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入小数格式 的本地化字符串。
        /// </summary>
        public static string Sys_PleaseInputDecimalFormat {
            get {
                return ResourceManager.GetString("Sys.PleaseInputDecimalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入下拉菜单中存在的数据 的本地化字符串。
        /// </summary>
        public static string Sys_PleaseInputExistData {
            get {
                return ResourceManager.GetString("Sys.PleaseInputExistData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入数字 的本地化字符串。
        /// </summary>
        public static string Sys_PleaseInputNumber {
            get {
                return ResourceManager.GetString("Sys.PleaseInputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入数字格式 的本地化字符串。
        /// </summary>
        public static string Sys_PleaseInputNumberFormat {
            get {
                return ResourceManager.GetString("Sys.PleaseInputNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入文本 的本地化字符串。
        /// </summary>
        public static string Sys_PleaseInputText {
            get {
                return ResourceManager.GetString("Sys.PleaseInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        public static string Sys_PleaseSelect {
            get {
                return ResourceManager.GetString("Sys.PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请上传模板文件 的本地化字符串。
        /// </summary>
        public static string Sys_PleaseUploadTemplate {
            get {
                return ResourceManager.GetString("Sys.PleaseUploadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览 的本地化字符串。
        /// </summary>
        public static string Sys_Preview {
            get {
                return ResourceManager.GetString("Sys.Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        public static string Sys_Print {
            get {
                return ResourceManager.GetString("Sys.Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条 的本地化字符串。
        /// </summary>
        public static string Sys_Record {
            get {
                return ResourceManager.GetString("Sys.Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条/页 的本地化字符串。
        /// </summary>
        public static string Sys_RecordsPerPage {
            get {
                return ResourceManager.GetString("Sys.RecordsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Sys_Refresh {
            get {
                return ResourceManager.GetString("Sys.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Sys_Reset {
            get {
                return ResourceManager.GetString("Sys.Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已回滚 的本地化字符串。
        /// </summary>
        public static string Sys_Rollback {
            get {
                return ResourceManager.GetString("Sys.Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行号 的本地化字符串。
        /// </summary>
        public static string Sys_RowIndex {
            get {
                return ResourceManager.GetString("Sys.RowIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string Sys_Search {
            get {
                return ResourceManager.GetString("Sys.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索条件 的本地化字符串。
        /// </summary>
        public static string Sys_SearchCondition {
            get {
                return ResourceManager.GetString("Sys.SearchCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string Sys_Select {
            get {
                return ResourceManager.GetString("Sys.Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已选择 的本地化字符串。
        /// </summary>
        public static string Sys_Selected {
            get {
                return ResourceManager.GetString("Sys.Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一行 的本地化字符串。
        /// </summary>
        public static string Sys_SelectOneRow {
            get {
                return ResourceManager.GetString("Sys.SelectOneRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最多只能选择一行 的本地化字符串。
        /// </summary>
        public static string Sys_SelectOneRowMax {
            get {
                return ResourceManager.GetString("Sys.SelectOneRowMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请至少选择一行 的本地化字符串。
        /// </summary>
        public static string Sys_SelectOneRowMin {
            get {
                return ResourceManager.GetString("Sys.SelectOneRowMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string Sys_Submit {
            get {
                return ResourceManager.GetString("Sys.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交失败 的本地化字符串。
        /// </summary>
        public static string Sys_SubmitFailed {
            get {
                return ResourceManager.GetString("Sys.SubmitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计： 的本地化字符串。
        /// </summary>
        public static string Sys_Total {
            get {
                return ResourceManager.GetString("Sys.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新成功 的本地化字符串。
        /// </summary>
        public static string Sys_UpdateDone {
            get {
                return ResourceManager.GetString("Sys.UpdateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传失败 的本地化字符串。
        /// </summary>
        public static string Sys_UploadFailed {
            get {
                return ResourceManager.GetString("Sys.UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传模板 的本地化字符串。
        /// </summary>
        public static string Sys_UploadTemplate {
            get {
                return ResourceManager.GetString("Sys.UploadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效 的本地化字符串。
        /// </summary>
        public static string Sys_Valid {
            get {
                return ResourceManager.GetString("Sys.Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 格式错误 的本地化字符串。
        /// </summary>
        public static string Sys_ValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("Sys.ValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的模板 的本地化字符串。
        /// </summary>
        public static string Sys_WrongTemplate {
            get {
                return ResourceManager.GetString("Sys.WrongTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本长度不符合要求 的本地化字符串。
        /// </summary>
        public static string Sys_WrongTextLength {
            get {
                return ResourceManager.GetString("Sys.WrongTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WTM文档 的本地化字符串。
        /// </summary>
        public static string Sys_WtmDoc {
            get {
                return ResourceManager.GetString("Sys.WtmDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Sys_Yes {
            get {
                return ResourceManager.GetString("Sys.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}格式错误 的本地化字符串。
        /// </summary>
        public static string Validate__0_formaterror {
            get {
                return ResourceManager.GetString("Validate.{0}formaterror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须是数字 的本地化字符串。
        /// </summary>
        public static string Validate__0_number {
            get {
                return ResourceManager.GetString("Validate.{0}number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}至少是{1} 的本地化字符串。
        /// </summary>
        public static string Validate__0_range_1_ {
            get {
                return ResourceManager.GetString("Validate.{0}range{1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须是{1}到{2}之间的数 的本地化字符串。
        /// </summary>
        public static string Validate__0_range_1__2_ {
            get {
                return ResourceManager.GetString("Validate.{0}range{1}{2}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}最多是{1} 的本地化字符串。
        /// </summary>
        public static string Validate__0_range_2_ {
            get {
                return ResourceManager.GetString("Validate.{0}range{2}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}是必填项 的本地化字符串。
        /// </summary>
        public static string Validate__0_required {
            get {
                return ResourceManager.GetString("Validate.{0}required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}最多输入{1}个字符 的本地化字符串。
        /// </summary>
        public static string Validate__0_stringmax_1_ {
            get {
                return ResourceManager.GetString("Validate.{0}stringmax{1}", resourceCulture);
            }
        }
    }
}
